let C,page="home",deferredPrompt;const app=document.getElementById("app");
async function start(){C=await fetch("config.json",{cache:"no-store"}).then(r=>r.json());render();if("serviceWorker"in navigator)navigator.serviceWorker.register("service-worker.js")}
function head(){return `<header><div><p class="eyebrow">YOUR DIGITAL STARTING POINT</p><h1>${C.workspace.name}</h1><p class="sub">${C.workspace.tagline}</p></div><div class="header-actions">${page!=="home"?'<button class="back" onclick="home()">← Back</button>':""}<button id="install" class="install" hidden>Install Focus Workspace</button></div></header>`}
function search(){return `<section class="searchbox"><h2>Search</h2><p>Choose where to search</p><form class="searchrow" onsubmit="doSearch(event)"><select id="engine" onchange="syncSearch()">${C.search.map((x,i)=>`<option value="${i}">${x.icon} ${x.label}</option>`).join("")}</select><input id="q" placeholder="What would you like to search for?"><button id="go">Search Google</button></form><p class="help">Search Google, ChatGPT, Gmail, Drive, OneDrive or NotebookLM from one place.</p></section>`}
function homePage(){return `${head()}${search()}<section class="grid">${[
["email","📧","Email","Choose an inbox"],["calendar","📅","Calendar","Choose a calendar"],["drive","📁","Drive","Open a folder"],["ai","🤖","AI","AI and building tools"],["projects","📋","Projects","Active work"],["settings","⚙️","Settings","Workspace options"]].map(x=>`<button class="card" onclick="openPage('${x[0]}')"><span>${x[1]}</span><b>${x[2]}</b><small>${x[3]}</small></button>`).join("")}</section><section class="focus"><h2>Today's top three</h2><input id="t1" placeholder="First priority"><input id="t2" placeholder="Second priority"><input id="t3" placeholder="Third priority"><button onclick="clearTasks()">Clear today</button></section><footer>Version ${C.workspace.version}</footer>`}
function listPage(title,icon,items){return `${head()}<div class="page-title"><span>${icon}</span><h2>${title}</h2></div><div class="list">${items.map(x=>`<a class="item" href="${x.url}" target="_blank"><span>${x.icon}</span><div><strong>${x.label}</strong><small>${x.email||"Open"}</small></div></a>`).join("")}</div>`}
function render(){if(page==="home")app.innerHTML=homePage();if(page==="email")app.innerHTML=listPage("Email","📧",C.email.map(x=>({...x,url:`https://mail.google.com/mail/?authuser=${encodeURIComponent(x.email)}`})));if(page==="calendar")app.innerHTML=listPage("Calendar","📅",C.calendar.map(x=>({...x,url:x.url||`https://calendar.google.com/calendar/u/0/r?authuser=${encodeURIComponent(x.email)}`})));if(page==="drive")app.innerHTML=listPage("Drive","📁",C.drive);if(page==="ai")app.innerHTML=listPage("AI","🤖",C.ai);if(page==="projects")app.innerHTML=listPage("Projects","📋",C.projects);if(page==="settings")app.innerHTML=`${head()}<div class="page-title"><span>⚙️</span><h2>Settings</h2></div><p>More settings will be added after the main layout is approved.</p>`;loadTasks();wireInstall();if(page==="home")syncSearch()}
function openPage(p){page=p;render();scrollTo(0,0)}function home(){page="home";render();scrollTo(0,0)}
function syncSearch(){const i=C.search[+document.getElementById("engine").value||0],q=document.getElementById("q"),b=document.getElementById("go");b.textContent=i.button;q.disabled=!i.query;q.placeholder=i.query?"What would you like to search for?":`${i.button} — no search term needed`;if(!i.query)q.value=""}
function doSearch(e){e.preventDefault();const i=C.search[+document.getElementById("engine").value||0],q=document.getElementById("q").value.trim();if(i.query&&!q)return document.getElementById("q").focus();open(i.query?i.url.replace("{query}",encodeURIComponent(q)):i.url,"_blank")}
function loadTasks(){["t1","t2","t3"].forEach(id=>{const e=document.getElementById(id);if(e){e.value=localStorage.getItem(id)||"";e.oninput=()=>localStorage.setItem(id,e.value)}})}
function clearTasks(){["t1","t2","t3"].forEach(id=>{localStorage.removeItem(id);const e=document.getElementById(id);if(e)e.value=""})}
function wireInstall(){const b=document.getElementById("install");if(b&&deferredPrompt){b.hidden=false;b.onclick=async()=>{deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;b.hidden=true}}}
addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;wireInstall()});start();